spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
debug: true
server:
  port: 8082