spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8088
debug: true